### ISSUE TITLE
use case excerise for lab02 (terence, nichloas, eng chun)

### ISSUE THREAD

**Issue by 3ngchun** [3ngchun/ICT2201_P7-10#15]
Lab 2 Use case exercise

**Comment by Terence2389** [comment]
![image](https://user-images.githubusercontent.com/94297073/190326814-73f72774-567a-477a-a3b7-b532bcd7b258.png)
Lab 2 Use case diagram

**Comment by Terence2389** [comment]
Lab 2 - Use Case Description
ID: UC-10
Name: View lead author decision
Description: Author would be able to view the status of their suggestions or amendment made to the lead author regarding the project.
Primary actor: Author
Preconditions: Lead Author approves or rejects the suggestion or amendments made by the author.
Main Success Scenario:
1.	Administrator create lead author and author
2.	Lead author create collaboration group
3.	Author join collaboration group
4.	Lead author create document
5.	Author make suggestion or amendment to document
6.	Lead author approve or reject author’s suggestion or amendment
7.	Author view status of suggestion or amendment
Postconditions:
1.	Main: Author will be able to see if his/her contribution is accepted by lead author or not.
