### ISSUE TITLE
improve GUI UI/UX

### ISSUE THREAD

**Issue by 3ngchun** [3ngchun/ICT2201_P7-10#22]

**Comment by 3ngchun** [comment]
To improve our GUI UI/UX, make it more user friendly and concise.

**Comment by 3ngchun** [comment]
added teacher's dashboard gui. swapped assignee to nich

**Comment by 3ngchun** [comment]
nicholas, how is the GUI coming around?

**Comment by 3ngchun** [comment]
nicholas, can update the GUI quickly? we need to review it

**Comment by 2101309** [comment]
Already updated in the M2 report on Google Docs.  Do review it and let me know the changes.

**Comment by 3ngchun** [comment]
The GUI u uploaded, is not align with the requirement..

**Comment by 3ngchun** [comment]
swap assignee to Marvin

**Comment by MarvinWSH** [comment]
Improved GUI UI/UX
